name: TFLint
on:
  push:
    branches:
      - '**'         # Match all branches
    paths:
      - '**/*.tf'    # Only trigger if Terraform files change

  pull_request:
    branches:
      - '**'         # All PRs, from any branch
    paths:
      - '**/*.tf'

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: latest # Or specify a specific version like 'v0.50.0'

      - name: Run TFLint
        run: tflint --init && tflint
